//! Configuration file loading and saving.
//!
//! Handles reading/writing the user's kernel config choices,
//! merging with schema defaults, and generating output.

use crate::schema::codegen::{CodeGenerator, ConfigValues};
use crate::schema::{ConfigSchema, ConfigType};
use anyhow::{Context, Result};
use std::collections::HashMap;
use std::fs;
use std::path::{Path, PathBuf};

/// Result of loading a configuration file.
#[derive(Debug)]
pub struct LoadResult {
    /// The loaded values (may be empty if new config).
    pub values: ConfigValues,
    /// Path where values were loaded from.
    pub path: PathBuf,
    /// Whether this was a new file (not existing).
    pub is_new: bool,
    /// Any warnings encountered during loading.
    pub warnings: Vec<String>,
}

/// Loads and manages kernel configuration files.
pub struct ConfigLoader {
    /// Directory to search for config files.
    search_dirs: Vec<PathBuf>,
    /// Default schema path.
    schema_path: PathBuf,
    /// Output path for generated config.
    output_path: PathBuf,
}

impl ConfigLoader {
    pub fn new(schema_path: impl Into<PathBuf>, output_path: impl Into<PathBuf>) -> Self {
        Self {
            search_dirs: vec![],
            schema_path: schema_path.into(),
            output_path: output_path.into(),
        }
    }

    /// Add a directory to search for config files.
    pub fn add_search_dir(mut self, dir: impl Into<PathBuf>) -> Self {
        self.search_dirs.push(dir.into());
        self
    }

    /// Load the configuration from a path, or return defaults if not found.
    pub fn load(&self, path: Option<&Path>) -> Result<LoadResult> {
        let path = self.find_config(path)?;
        let is_new = !path.exists();

        if is_new {
            return Ok(LoadResult {
                values: HashMap::new(),
                path,
                is_new: true,
                warnings: vec![],
            });
        }

        let content = fs::read_to_string(&path)
            .with_context(|| format!("Failed to read config: {}", path.display()))?;

        self.parse_values(&content, &path)
    }

    /// Find the config file path, trying multiple locations.
    fn find_config(&self, explicit: Option<&Path>) -> Result<PathBuf> {
        // Explicit path first
        if let Some(p) = explicit {
            return Ok(p.to_path_buf());
        }

        // Search in configured directories
        for dir in &self.search_dirs {
            let candidates = [
                dir.join(".ionix.config"),
                dir.join("kernel.config"),
                dir.join("config.toml"),
            ];

            for candidate in candidates {
                if candidate.exists() {
                    return Ok(candidate);
                }
            }
        }

        // Default to current directory
        Ok(PathBuf::from("kernel.config"))
    }

    /// Parse configuration values from TOML content.
    fn parse_values(&self, content: &str, path: &Path) -> Result<LoadResult> {
        // Skip ionix annotations: remove header line and all comment lines
        let content: String = content
            .lines()
            .filter(|line| {
                let trimmed = line.trim();
                // Keep lines that are not comments
                !trimmed.starts_with('#')
            })
            .collect::<Vec<_>>()
            .join("\n");

        let values: ConfigValues = toml::from_str(&content)
            .with_context(|| format!("Failed to parse config: {}", path.display()))?;

        let mut warnings = Vec::new();

        // Validate loaded keys exist in schema (only if schema exists)
        if self.schema_path.exists() {
            if let Ok(schema) = ConfigSchema::from_path(&self.schema_path) {
                for key in values.keys() {
                    if schema.get(key).is_none() {
                        warnings.push(format!(
                            "Unknown config key '{}' in config file - ignoring",
                            key
                        ));
                    }
                }
            }
        }

        Ok(LoadResult {
            values,
            path: path.to_path_buf(),
            is_new: false,
            warnings,
        })
    }

    /// Header comment for config files
    pub const CONFIG_HEADER: &str = r#"# Generated by ionix - DO NOT EDIT
"#;

    /// Save configuration values to the current working directory as `.config.toml`.
    /// If `.config.toml` already exists, backup to `.config.old.toml` first.
    /// Only saves if there are actual modifications.
    pub fn save_to_cwd(&self, values: &ConfigValues) -> Result<bool> {
        self.save_if_changed(
            values,
            Path::new(".config.toml"),
            Some(Path::new(".config.old.toml")),
        )
    }

    /// Save configuration values to a TOML file.
    /// If the file already exists, backs it up as `<stem>.old.toml` before overwriting.
    pub fn save(&self, values: &ConfigValues, path: &Path) -> Result<bool> {
        let backup_path = default_backup_path(path);
        self.save_if_changed(values, path, Some(&backup_path))
    }

    /// Save configuration values and use an explicit backup path.
    /// Returns true when the config file was written.
    pub fn save_if_changed(
        &self,
        values: &ConfigValues,
        path: &Path,
        backup_path: Option<&Path>,
    ) -> Result<bool> {
        self.save_rendered_if_changed(&render_config(values, None)?, path, backup_path)
    }

    /// Save configuration values in schema order and use an explicit backup path.
    /// Returns true when the config file was written.
    pub fn save_with_schema_if_changed(
        &self,
        values: &ConfigValues,
        schema: &ConfigSchema,
        path: &Path,
        backup_path: Option<&Path>,
    ) -> Result<bool> {
        self.save_rendered_if_changed(&render_config(values, Some(schema))?, path, backup_path)
    }

    fn save_rendered_if_changed(
        &self,
        output: &str,
        path: &Path,
        backup_path: Option<&Path>,
    ) -> Result<bool> {
        // Ensure parent directory exists
        if let Some(parent) = path.parent() {
            if !parent.as_os_str().is_empty() && !parent.exists() {
                fs::create_dir_all(parent)
                    .with_context(|| format!("Failed to create directory: {}", parent.display()))?;
            }
        }

        if path.exists() {
            let old = fs::read_to_string(path).unwrap_or_default();
            if old == output {
                return Ok(false);
            }

            if let Some(backup_path) = backup_path {
                if let Some(parent) = backup_path.parent() {
                    if !parent.as_os_str().is_empty() && !parent.exists() {
                        fs::create_dir_all(parent).with_context(|| {
                            format!("Failed to create directory: {}", parent.display())
                        })?;
                    }
                }
                fs::copy(path, backup_path).with_context(|| {
                    format!(
                        "Failed to backup config {} to {}",
                        path.display(),
                        backup_path.display()
                    )
                })?;
            }
        }

        fs::write(path, output)
            .with_context(|| format!("Failed to write config: {}", path.display()))?;

        Ok(true)
    }

    /// Generate the Rust config file from current values.
    pub fn generate(&self, schema: &ConfigSchema, values: &ConfigValues) -> Result<()> {
        // Ensure parent directory exists
        if let Some(parent) = self.output_path.parent() {
            if !parent.exists() {
                fs::create_dir_all(parent)
                    .with_context(|| format!("Failed to create directory: {}", parent.display()))?;
            }
        }

        let generator = CodeGenerator::new(schema, values);
        generator.write_to_file(&self.output_path)?;
        Ok(())
    }

    /// Merge user values with schema defaults.
    pub fn merge_with_defaults(values: &ConfigValues, schema: &ConfigSchema) -> ConfigValues {
        let mut merged = values.clone();

        for item in schema.items() {
            if !merged.contains_key(&item.key) {
                merged.insert(item.key.clone(), item.default.clone());
            }
        }

        merged
    }

    /// Validate values against schema constraints.
    /// Returns errors for:
    /// - Missing keys (schema has but config doesn't)
    /// - Type mismatches
    /// - Invalid values (out of range)
    /// Ignores extra keys in config that aren't in schema.
    pub fn validate(values: &ConfigValues, schema: &ConfigSchema) -> Vec<String> {
        let mut errors = Vec::new();

        // Check for missing keys (schema has but config doesn't)
        for item in schema.items() {
            if !values.contains_key(&item.key) {
                errors.push(format!("Missing key in config: {}", item.key));
            }
        }

        // Check type and value validity
        for (key, value) in values {
            let Some(item) = schema.get(key) else {
                // Extra keys in config are ignored
                continue;
            };

            // Type check
            let type_ok = match (item.config_type, value) {
                (ConfigType::Bool, toml::Value::Boolean(_)) => true,
                (ConfigType::String, toml::Value::String(_)) => true,
                (ConfigType::U8, toml::Value::Integer(i)) => (0..=255).contains(i),
                (ConfigType::U16, toml::Value::Integer(i)) => (0..=65535).contains(i),
                (
                    ConfigType::U32 | ConfigType::U64 | ConfigType::Usize,
                    toml::Value::Integer(i),
                ) => *i >= 0,
                (
                    ConfigType::U8
                    | ConfigType::U16
                    | ConfigType::U32
                    | ConfigType::U64
                    | ConfigType::Usize,
                    toml::Value::String(s),
                ) => Self::unsigned_literal_fits(s, item.config_type),
                _ => false,
            };

            if !type_ok {
                errors.push(format!(
                    "Invalid value for '{}': expected {}, got {:?}",
                    key, item.config_type, value
                ));
            }
        }

        for item in schema.items() {
            if item.config_type != ConfigType::Bool
                || !values
                    .get(&item.key)
                    .and_then(|value| value.as_bool())
                    .unwrap_or(false)
            {
                continue;
            }

            for conflict in &item.conflicts_with {
                if values
                    .get(conflict)
                    .and_then(|value| value.as_bool())
                    .unwrap_or(false)
                {
                    errors.push(format!(
                        "Invalid config: '{}' conflicts with '{}'",
                        item.key, conflict
                    ));
                }
            }
        }

        errors
    }

    fn unsigned_literal_fits(s: &str, expected: ConfigType) -> bool {
        parse_unsigned_literal(s)
            .map(|value| value <= max_value_for_type(expected))
            .unwrap_or(false)
    }

    /// Get the default config file path.
    pub fn default_config_path() -> PathBuf {
        dirs::config_dir()
            .unwrap_or_else(|| PathBuf::from("."))
            .join("ionix")
            .join("kernel.config")
    }

    /// Get the default schema file path.
    pub fn default_schema_path() -> PathBuf {
        PathBuf::from("kernel.kconfig")
    }
}

fn default_backup_path(path: &Path) -> PathBuf {
    path.with_extension("old.toml")
}

fn render_config(values: &ConfigValues, schema: Option<&ConfigSchema>) -> Result<String> {
    let mut out = String::from(ConfigLoader::CONFIG_HEADER);

    if let Some(schema) = schema {
        for item in schema.items() {
            if let Some(value) = values.get(&item.key) {
                out.push_str(&item.key);
                out.push_str(" = ");
                out.push_str(&format_value(value)?);
                out.push('\n');
            }
        }

        let mut extras: Vec<_> = values
            .keys()
            .filter(|key| schema.get(key).is_none())
            .cloned()
            .collect();
        extras.sort();
        for key in extras {
            if let Some(value) = values.get(&key) {
                out.push_str(&key);
                out.push_str(" = ");
                out.push_str(&format_value(value)?);
                out.push('\n');
            }
        }
    } else {
        let mut keys: Vec<_> = values.keys().cloned().collect();
        keys.sort();
        for key in keys {
            if let Some(value) = values.get(&key) {
                out.push_str(&key);
                out.push_str(" = ");
                out.push_str(&format_value(value)?);
                out.push('\n');
            }
        }
    }

    Ok(out)
}

fn format_value(value: &toml::Value) -> Result<String> {
    match value {
        toml::Value::Boolean(value) => Ok(value.to_string()),
        toml::Value::Integer(value) => Ok(value.to_string()),
        toml::Value::String(value) => Ok(escape_toml_string(value)),
        _ => toml::to_string(value)
            .map(|s| s.trim().to_string())
            .context("Failed to serialize config value"),
    }
}

fn escape_toml_string(value: &str) -> String {
    let mut out = String::with_capacity(value.len() + 2);
    out.push('"');
    for ch in value.chars() {
        match ch {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if c.is_control() => {
                use std::fmt::Write;
                let _ = write!(out, "\\u{{{:x}}}", c as u32);
            }
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

fn max_value_for_type(config_type: ConfigType) -> u128 {
    match config_type {
        ConfigType::U8 => u8::MAX as u128,
        ConfigType::U16 => u16::MAX as u128,
        ConfigType::U32 => u32::MAX as u128,
        ConfigType::U64 => u64::MAX as u128,
        ConfigType::Usize => usize::MAX as u128,
        ConfigType::Bool | ConfigType::String => 0,
    }
}

fn parse_unsigned_literal(s: &str) -> Option<u128> {
    let (base, digits) = if let Some(rest) = s.strip_prefix("0x").or_else(|| s.strip_prefix("0X")) {
        (16, rest)
    } else if let Some(rest) = s.strip_prefix("0b").or_else(|| s.strip_prefix("0B")) {
        (2, rest)
    } else {
        return None;
    };

    if digits.is_empty() || !digits.chars().any(|c| c != '_') {
        return None;
    }

    let mut value = 0u128;
    for ch in digits.chars() {
        if ch == '_' {
            continue;
        }
        let digit = ch.to_digit(base)?;
        value = value.checked_mul(base as u128)?;
        value = value.checked_add(digit as u128)?;
    }
    Some(value)
}

impl Default for ConfigLoader {
    fn default() -> Self {
        Self::new(
            Self::default_schema_path(),
            PathBuf::from("generated_config.rs"),
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_merge_with_defaults() {
        let toml = r#"
[[items]]
name = "Test Bool"
key = "TEST_BOOL"
type = "bool"
default = true

[[items]]
name = "Test Num"
key = "TEST_NUM"
type = "u64"
default = 42
"#;
        let schema = ConfigSchema::from_str(toml).unwrap();

        let mut values = ConfigValues::new();
        values.insert("TEST_BOOL".to_string(), toml::Value::Boolean(false));

        let merged = ConfigLoader::merge_with_defaults(&values, &schema);

        assert_eq!(merged.get("TEST_BOOL").unwrap().as_bool(), Some(false));
        assert_eq!(merged.get("TEST_NUM").unwrap().as_integer(), Some(42));
    }
}
