//! Configuration file loading and saving.
//!
//! Handles reading/writing the user's kernel config choices,
//! merging with schema defaults, and generating output.

use crate::schema::codegen::{CodeGenerator, ConfigValues};
use crate::schema::{ConfigSchema, ConfigType};
use anyhow::{Context, Result};
use std::collections::HashMap;
use std::fs;
use std::path::{Path, PathBuf};

/// Result of loading a configuration file.
#[derive(Debug)]
pub struct LoadResult {
    /// The loaded values (may be empty if new config).
    pub values: ConfigValues,
    /// Path where values were loaded from.
    pub path: PathBuf,
    /// Whether this was a new file (not existing).
    pub is_new: bool,
    /// Any warnings encountered during loading.
    pub warnings: Vec<String>,
}

/// Loads and manages kernel configuration files.
pub struct ConfigLoader {
    /// Directory to search for config files.
    search_dirs: Vec<PathBuf>,
    /// Default schema path.
    schema_path: PathBuf,
    /// Output path for generated config.
    output_path: PathBuf,
}

impl ConfigLoader {
    pub fn new(schema_path: impl Into<PathBuf>, output_path: impl Into<PathBuf>) -> Self {
        Self {
            search_dirs: vec![],
            schema_path: schema_path.into(),
            output_path: output_path.into(),
        }
    }

    /// Add a directory to search for config files.
    pub fn add_search_dir(mut self, dir: impl Into<PathBuf>) -> Self {
        self.search_dirs.push(dir.into());
        self
    }

    /// Load the configuration from a path, or return defaults if not found.
    pub fn load(&self, path: Option<&Path>) -> Result<LoadResult> {
        let path = self.find_config(path)?;
        let is_new = !path.exists();

        if is_new {
            return Ok(LoadResult {
                values: HashMap::new(),
                path,
                is_new: true,
                warnings: vec![],
            });
        }

        let content = fs::read_to_string(&path)
            .with_context(|| format!("Failed to read config: {}", path.display()))?;

        self.parse_values(&content, &path)
    }

    /// Find the config file path, trying multiple locations.
    fn find_config(&self, explicit: Option<&Path>) -> Result<PathBuf> {
        // Explicit path first
        if let Some(p) = explicit {
            return Ok(p.to_path_buf());
        }

        // Search in configured directories
        for dir in &self.search_dirs {
            let candidates = [
                dir.join(".ionix.config"),
                dir.join("kernel.config"),
                dir.join("config.toml"),
            ];

            for candidate in candidates {
                if candidate.exists() {
                    return Ok(candidate);
                }
            }
        }

        // Default to current directory
        Ok(PathBuf::from("kernel.config"))
    }

    /// Parse configuration values from TOML content.
    fn parse_values(&self, content: &str, path: &Path) -> Result<LoadResult> {
        // Skip ionix annotations: remove header line and all comment lines
        let content: String = content
            .lines()
            .filter(|line| {
                let trimmed = line.trim();
                // Keep lines that are not comments
                !trimmed.starts_with('#')
            })
            .collect::<Vec<_>>()
            .join("\n");

        let values: ConfigValues = toml::from_str(&content)
            .with_context(|| format!("Failed to parse config: {}", path.display()))?;

        let mut warnings = Vec::new();

        // Validate loaded keys exist in schema (only if schema exists)
        if self.schema_path.exists() {
            if let Ok(schema) = ConfigSchema::from_path(&self.schema_path) {
                for key in values.keys() {
                    if schema.get(key).is_none() {
                        warnings.push(format!("Unknown config key '{}' in config file - ignoring", key));
                    }
                }
            }
        }

        Ok(LoadResult {
            values,
            path: path.to_path_buf(),
            is_new: false,
            warnings,
        })
    }

    /// Header comment for config files
    pub const CONFIG_HEADER: &str = r#"# Generated by ionix - DO NOT EDIT
"#;

    /// Save configuration values to the current working directory as `config.toml`.
    /// If `config.toml` already exists, backup to `config.old.toml` first.
    /// Only saves if there are actual modifications.
    pub fn save_to_cwd(&self, values: &ConfigValues) -> Result<bool> {
        if values.is_empty() {
            return Ok(false);
        }

        let config_path = PathBuf::from("config.toml");

        // Backup existing config.toml to config.old.toml
        if config_path.exists() {
            let backup_path = PathBuf::from("config.old.toml");
            let _ = fs::copy(&config_path, &backup_path);
        }

        let content = toml::to_string_pretty(values)
            .context("Failed to serialize config")?;

        // Add header comment
        let output = format!("{}{}", Self::CONFIG_HEADER, content);

        fs::write(&config_path, output)
            .with_context(|| format!("Failed to write config: {}", config_path.display()))?;

        Ok(true)
    }

    /// Save configuration values to a TOML file.
    /// If the file already exists, backs it up as `<filename>.old` in the CWD before overwriting.
    pub fn save(&self, values: &ConfigValues, path: &Path) -> Result<()> {
        // Ensure parent directory exists
        if let Some(parent) = path.parent() {
            if !parent.exists() {
                fs::create_dir_all(parent)
                    .with_context(|| format!("Failed to create directory: {}", parent.display()))?;
            }
        }

        // Backup existing TOML file to CWD as <filename>.old
        if path.exists() {
            let filename = path.file_name().map(|n| n.to_string_lossy().to_string()).unwrap_or("config".to_string());
            let backup_path = PathBuf::from(format!("{}.old", filename));
            let _ = fs::copy(path, &backup_path);
        }

        let content = toml::to_string_pretty(values)
            .context("Failed to serialize config")?;

        // Add header comment
        let output = format!("{}{}", Self::CONFIG_HEADER, content);

        fs::write(path, output)
            .with_context(|| format!("Failed to write config: {}", path.display()))?;

        Ok(())
    }

    /// Generate the Rust config file from current values.
    pub fn generate(&self, schema: &ConfigSchema, values: &ConfigValues) -> Result<()> {
        // Ensure parent directory exists
        if let Some(parent) = self.output_path.parent() {
            if !parent.exists() {
                fs::create_dir_all(parent)
                    .with_context(|| format!("Failed to create directory: {}", parent.display()))?;
            }
        }

        let generator = CodeGenerator::new(schema, values);
        generator.write_to_file(&self.output_path)?;
        Ok(())
    }

    /// Merge user values with schema defaults.
    pub fn merge_with_defaults(values: &ConfigValues, schema: &ConfigSchema) -> ConfigValues {
        let mut merged = values.clone();

        for item in schema.items() {
            if !merged.contains_key(&item.key) {
                merged.insert(item.key.clone(), item.default.clone());
            }
        }

        merged
    }

    /// Validate values against schema constraints.
    /// Returns errors for:
    /// - Missing keys (schema has but config doesn't)
    /// - Type mismatches
    /// - Invalid values (out of range)
    /// Ignores extra keys in config that aren't in schema.
    pub fn validate(values: &ConfigValues, schema: &ConfigSchema) -> Vec<String> {
        let mut errors = Vec::new();

        // Check for missing keys (schema has but config doesn't)
        for item in schema.items() {
            if !values.contains_key(&item.key) {
                errors.push(format!("Missing key in config: {}", item.key));
            }
        }

        // Check type and value validity
        for (key, value) in values {
            let Some(item) = schema.get(key) else {
                // Extra keys in config are ignored
                continue;
            };

            // Type check
            let type_ok = match (item.config_type, value) {
                (ConfigType::Bool, toml::Value::Boolean(_)) => true,
                (ConfigType::String, toml::Value::String(_)) => true,
                (ConfigType::U8, toml::Value::Integer(i)) => (0..=255).contains(i),
                (ConfigType::U16, toml::Value::Integer(i)) => (0..=65535).contains(i),
                (ConfigType::U32 | ConfigType::U64 | ConfigType::Usize, toml::Value::Integer(i)) => *i >= 0,
                _ => false,
            };

            if !type_ok {
                errors.push(format!(
                    "Invalid value for '{}': expected {}, got {:?}",
                    key, item.config_type, value
                ));
            }
        }

        errors
    }

    /// Get the default config file path.
    pub fn default_config_path() -> PathBuf {
        dirs::config_dir()
            .unwrap_or_else(|| PathBuf::from("."))
            .join("ionix")
            .join("kernel.config")
    }

    /// Get the default schema file path.
    pub fn default_schema_path() -> PathBuf {
        PathBuf::from("kernel.kconfig")
    }
}

impl Default for ConfigLoader {
    fn default() -> Self {
        Self::new(
            Self::default_schema_path(),
            PathBuf::from("generated_config.rs"),
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_merge_with_defaults() {
        let toml = r#"
[[items]]
name = "Test Bool"
key = "TEST_BOOL"
type = "bool"
default = true

[[items]]
name = "Test Num"
key = "TEST_NUM"
type = "u64"
default = 42
"#;
        let schema = ConfigSchema::from_str(toml).unwrap();

        let mut values = ConfigValues::new();
        values.insert("TEST_BOOL".to_string(), toml::Value::Boolean(false));

        let merged = ConfigLoader::merge_with_defaults(&values, &schema);

        assert_eq!(merged.get("TEST_BOOL").unwrap().as_bool(), Some(false));
        assert_eq!(merged.get("TEST_NUM").unwrap().as_integer(), Some(42));
    }
}